---
dependencies:
  - role: apt-repos
    repos:
      - repo: 'deb {{ apt_repos.bbg_ubuntu.repo }} {{ ansible_lsb.codename }} main'
        key_url: '{{ apt_repos.bbg_ubuntu.key_url }}'
      - repo: 'deb {{ apt_repos.hwraid.repo }} precise main'
        key_url: '{{ apt_repos.hwraid.key_url }}'
      - repo: 'deb {{ apt_repos.sensu.repo }} sensu main'
        key_url: '{{ apt_repos.sensu.key_url }}'
        validate_certs: no
  - role: docker
    when: docker.enabled is defined and docker.enabled|bool
  - role: monitoring-common
    when: monitoring.enabled is not defined or monitoring.enabled|bool
